// Code generated by ent, DO NOT EDIT.

package chatent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fanchunke/xgpt3/conversation/ent/chatent/message"
	"github.com/fanchunke/xgpt3/conversation/ent/chatent/session"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSessionID sets the "session_id" field.
func (mc *MessageCreate) SetSessionID(i int) *MessageCreate {
	mc.mutation.SetSessionID(i)
	return mc
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (mc *MessageCreate) SetNillableSessionID(i *int) *MessageCreate {
	if i != nil {
		mc.SetSessionID(*i)
	}
	return mc
}

// SetFromUserID sets the "from_user_id" field.
func (mc *MessageCreate) SetFromUserID(s string) *MessageCreate {
	mc.mutation.SetFromUserID(s)
	return mc
}

// SetToUserID sets the "to_user_id" field.
func (mc *MessageCreate) SetToUserID(s string) *MessageCreate {
	mc.mutation.SetToUserID(s)
	return mc
}

// SetContent sets the "content" field.
func (mc *MessageCreate) SetContent(s string) *MessageCreate {
	mc.mutation.SetContent(s)
	return mc
}

// SetSpouseID sets the "spouse_id" field.
func (mc *MessageCreate) SetSpouseID(i int) *MessageCreate {
	mc.mutation.SetSpouseID(i)
	return mc
}

// SetNillableSpouseID sets the "spouse_id" field if the given value is not nil.
func (mc *MessageCreate) SetNillableSpouseID(i *int) *MessageCreate {
	if i != nil {
		mc.SetSpouseID(*i)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MessageCreate) SetCreatedAt(t time.Time) *MessageCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MessageCreate) SetNillableCreatedAt(t *time.Time) *MessageCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetSpouse sets the "spouse" edge to the Message entity.
func (mc *MessageCreate) SetSpouse(m *Message) *MessageCreate {
	return mc.SetSpouseID(m.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (mc *MessageCreate) SetSession(s *Session) *MessageCreate {
	return mc.SetSessionID(s.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mc *MessageCreate) Mutation() *MessageMutation {
	return mc.mutation
}

// Save creates the Message in the database.
func (mc *MessageCreate) Save(ctx context.Context) (*Message, error) {
	mc.defaults()
	return withHooks[*Message, MessageMutation](ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MessageCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MessageCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MessageCreate) defaults() {
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := message.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MessageCreate) check() error {
	if _, ok := mc.mutation.FromUserID(); !ok {
		return &ValidationError{Name: "from_user_id", err: errors.New(`chatent: missing required field "Message.from_user_id"`)}
	}
	if _, ok := mc.mutation.ToUserID(); !ok {
		return &ValidationError{Name: "to_user_id", err: errors.New(`chatent: missing required field "Message.to_user_id"`)}
	}
	if _, ok := mc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`chatent: missing required field "Message.content"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`chatent: missing required field "Message.created_at"`)}
	}
	return nil
}

func (mc *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: message.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: message.FieldID,
			},
		}
	)
	_spec.OnConflict = mc.conflict
	if value, ok := mc.mutation.FromUserID(); ok {
		_spec.SetField(message.FieldFromUserID, field.TypeString, value)
		_node.FromUserID = value
	}
	if value, ok := mc.mutation.ToUserID(); ok {
		_spec.SetField(message.FieldToUserID, field.TypeString, value)
		_node.ToUserID = value
	}
	if value, ok := mc.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := mc.mutation.SpouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   message.SpouseTable,
			Columns: []string{message.SpouseColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: message.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SpouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: session.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Message.Create().
//		SetSessionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
//
func (mc *MessageCreate) OnConflict(opts ...sql.ConflictOption) *MessageUpsertOne {
	mc.conflict = opts
	return &MessageUpsertOne{
		create: mc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mc *MessageCreate) OnConflictColumns(columns ...string) *MessageUpsertOne {
	mc.conflict = append(mc.conflict, sql.ConflictColumns(columns...))
	return &MessageUpsertOne{
		create: mc,
	}
}

type (
	// MessageUpsertOne is the builder for "upsert"-ing
	//  one Message node.
	MessageUpsertOne struct {
		create *MessageCreate
	}

	// MessageUpsert is the "OnConflict" setter.
	MessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetSessionID sets the "session_id" field.
func (u *MessageUpsert) SetSessionID(v int) *MessageUpsert {
	u.Set(message.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateSessionID() *MessageUpsert {
	u.SetExcluded(message.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *MessageUpsert) ClearSessionID() *MessageUpsert {
	u.SetNull(message.FieldSessionID)
	return u
}

// SetFromUserID sets the "from_user_id" field.
func (u *MessageUpsert) SetFromUserID(v string) *MessageUpsert {
	u.Set(message.FieldFromUserID, v)
	return u
}

// UpdateFromUserID sets the "from_user_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateFromUserID() *MessageUpsert {
	u.SetExcluded(message.FieldFromUserID)
	return u
}

// SetToUserID sets the "to_user_id" field.
func (u *MessageUpsert) SetToUserID(v string) *MessageUpsert {
	u.Set(message.FieldToUserID, v)
	return u
}

// UpdateToUserID sets the "to_user_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateToUserID() *MessageUpsert {
	u.SetExcluded(message.FieldToUserID)
	return u
}

// SetContent sets the "content" field.
func (u *MessageUpsert) SetContent(v string) *MessageUpsert {
	u.Set(message.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MessageUpsert) UpdateContent() *MessageUpsert {
	u.SetExcluded(message.FieldContent)
	return u
}

// SetSpouseID sets the "spouse_id" field.
func (u *MessageUpsert) SetSpouseID(v int) *MessageUpsert {
	u.Set(message.FieldSpouseID, v)
	return u
}

// UpdateSpouseID sets the "spouse_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateSpouseID() *MessageUpsert {
	u.SetExcluded(message.FieldSpouseID)
	return u
}

// ClearSpouseID clears the value of the "spouse_id" field.
func (u *MessageUpsert) ClearSpouseID() *MessageUpsert {
	u.SetNull(message.FieldSpouseID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *MessageUpsertOne) UpdateNewValues() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(message.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Message.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *MessageUpsertOne) Ignore() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageUpsertOne) DoNothing() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageCreate.OnConflict
// documentation for more info.
func (u *MessageUpsertOne) Update(set func(*MessageUpsert)) *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *MessageUpsertOne) SetSessionID(v int) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateSessionID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *MessageUpsertOne) ClearSessionID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.ClearSessionID()
	})
}

// SetFromUserID sets the "from_user_id" field.
func (u *MessageUpsertOne) SetFromUserID(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetFromUserID(v)
	})
}

// UpdateFromUserID sets the "from_user_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateFromUserID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateFromUserID()
	})
}

// SetToUserID sets the "to_user_id" field.
func (u *MessageUpsertOne) SetToUserID(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetToUserID(v)
	})
}

// UpdateToUserID sets the "to_user_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateToUserID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateToUserID()
	})
}

// SetContent sets the "content" field.
func (u *MessageUpsertOne) SetContent(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateContent() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateContent()
	})
}

// SetSpouseID sets the "spouse_id" field.
func (u *MessageUpsertOne) SetSpouseID(v int) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetSpouseID(v)
	})
}

// UpdateSpouseID sets the "spouse_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateSpouseID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateSpouseID()
	})
}

// ClearSpouseID clears the value of the "spouse_id" field.
func (u *MessageUpsertOne) ClearSpouseID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.ClearSpouseID()
	})
}

// Exec executes the query.
func (u *MessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("chatent: missing options for MessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MessageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MessageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	builders []*MessageCreate
	conflict []sql.ConflictOption
}

// Save creates the Message entities in the database.
func (mcb *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Message, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Message.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
//
func (mcb *MessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *MessageUpsertBulk {
	mcb.conflict = opts
	return &MessageUpsertBulk{
		create: mcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mcb *MessageCreateBulk) OnConflictColumns(columns ...string) *MessageUpsertBulk {
	mcb.conflict = append(mcb.conflict, sql.ConflictColumns(columns...))
	return &MessageUpsertBulk{
		create: mcb,
	}
}

// MessageUpsertBulk is the builder for "upsert"-ing
// a bulk of Message nodes.
type MessageUpsertBulk struct {
	create *MessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *MessageUpsertBulk) UpdateNewValues() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(message.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *MessageUpsertBulk) Ignore() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageUpsertBulk) DoNothing() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageCreateBulk.OnConflict
// documentation for more info.
func (u *MessageUpsertBulk) Update(set func(*MessageUpsert)) *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *MessageUpsertBulk) SetSessionID(v int) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateSessionID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *MessageUpsertBulk) ClearSessionID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.ClearSessionID()
	})
}

// SetFromUserID sets the "from_user_id" field.
func (u *MessageUpsertBulk) SetFromUserID(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetFromUserID(v)
	})
}

// UpdateFromUserID sets the "from_user_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateFromUserID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateFromUserID()
	})
}

// SetToUserID sets the "to_user_id" field.
func (u *MessageUpsertBulk) SetToUserID(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetToUserID(v)
	})
}

// UpdateToUserID sets the "to_user_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateToUserID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateToUserID()
	})
}

// SetContent sets the "content" field.
func (u *MessageUpsertBulk) SetContent(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateContent() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateContent()
	})
}

// SetSpouseID sets the "spouse_id" field.
func (u *MessageUpsertBulk) SetSpouseID(v int) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetSpouseID(v)
	})
}

// UpdateSpouseID sets the "spouse_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateSpouseID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateSpouseID()
	})
}

// ClearSpouseID clears the value of the "spouse_id" field.
func (u *MessageUpsertBulk) ClearSpouseID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.ClearSpouseID()
	})
}

// Exec executes the query.
func (u *MessageUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("chatent: OnConflict was set for builder %d. Set it on the MessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("chatent: missing options for MessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
